version: '3'

networks:
  web-shop:
    driver: bridge

services:

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "tempoSearch tempoServiceGraph"
      GF_INSTALL_PLUGINS: grafana-k6-app
    networks:
      - web-shop

  prometheus:
    build: ./prometheus
    ports:
      - "9090" 
    networks:
      - web-shop

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
    networks:
      - web-shop

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - web-shop

  shopping-cart:
    image: "condla/shopping-cart:1.1"
    ports:
      - "5555:5555"
    environment:
      SQLALCHEMY_DATABASE_URI: mariadb+mariadbconnector://root:myrootpassword@mariadb:3306/webshop
      OTEL_EXPORTER_OTLP_ENDPOINT: http://agent:4317
    depends_on:
      mariadb:
        condition: service_healthy
      
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
 
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: myrootpassword
      MARIADB_DATABASE: webshop
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
    healthcheck:
#      test: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pmyrootpassword"]
      test: mysqladmin ping -h 127.0.0.1 -uroot -pmyrootpassword
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  agent:
    image: grafana/agent:latest
    ports:
      - "80"
      - "6832"
      - "55679"
      - "4317:4317"
      - "1234:1234"
    volumes:
      - "${PWD}/agent/config.yaml:/etc/agent/agent.yaml"
    networks:
      - web-shop

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200"
      - "4317"
      - "55680"
      - "55681"
      - "14250"
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - web-shop

  products:
    image: "condla/products:otel-1.0"
    ports:
      - "8080:8080"
    environment:
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER: "otlp_span"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=products,team.name=backend,environment=production"
      JAVA_OPTS: "-javaagent:/opentelemetry-javaagent.jar"
    networks:
      - web-shop
    depends_on:
      - "shopping-cart"
      - "broker"
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  web-shop:
    image: "condla/web-shop:1.1"
    ports:
      - "3389:6666"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
    depends_on:
      - "shopping-cart"
    networks:
      - web-shop
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - web-shop

  broker:
    image: confluentinc/cp-server:7.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CREATE_TOPICS: audit:1:1,networkevents:1:1,webserverlogs:1:1,dbcommits:1:1,machine1:1:1,machine2:1:1
      #KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - web-shop

#  shop-simulator:
#    image: "condla/shop-simulator:1.0"
#    depends_on:
#      - "web-shop"
#    networks:
#      - web-shop
#    restart: on-failure

  blackbox_exporter:
    image: prom/blackbox-exporter:master
    volumes:
        - ./blackbox_exporter:/config
    command: --config.file=/config/blackbox.yml
    ports:
      - 9115:9115
